### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by Claycorp** [TelepathicGrunt/UltraAmplifiedMod#2] opened 2019-08-28 15:15 UTC
https://pastebin.com/4j3EZpAt

**Comment by Claycorp** [comment] 2019-08-28 15:48
Could have been my fault, I was stepping through trying to pinpoint it and found a fair few fabric mods that got downloaded because people don't mark/say they are fabric....
Feel free to close if you don't think it's an issue.

**Comment by TelepathicGrunt** [comment] 2019-09-17 18:42
Well this is a forge mod and you are on the 1.14 branch which is not as stable as the master branch. I remember dealing with that bug a bit ago but it should be fixed by now. Try this mod on the latest forge version and mod version and see if the issue persist.

**Comment by TelepathicGrunt** [comment] 2019-09-20 15:47
If the issue is still present on the latest release, please open up a new issue. Hopefully it'll work for you now!

**Closed as completed** 2019-09-20 15:46 UTC
Labels: bug
