### ISSUE TITLE
Crash when returning to overworld though RandomPortals portal

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TelepathicGrunt/UltraAmplifiedMod#4] opened 2019-12-14 23:15 UTC
My game crashes (incosistently, about every other time) when I'm returning to the overworld through a custom portal created through RandomPortals. My overworld was is using the ultra-amplified type. I was able to replicate the crash with this mod installed across several worlds and several game restarts. I've not been able to replicate the crash with ultra amplified removed. 

[latest.log](https://pastebin.com/dbcUNGyA)
This only contains the portion since my character logged in (to a freshly generated world), as the whole log couldn't be uploaded.

**Comment by TelepathicGrunt** [comment] 2019-12-15 15:16
Thank you for reporting this issue! I noticed you are using the 1.12.2 version of the mod which has quite a few worldgen flaws I couldn't fix until I moved to 1.13 and onward. The issue is indeed with my mod but I am having trouble replicating the crash so I can figure out what to patch.

My guess is it is something to do with either the Cave Cavities or a specific biome which would explain why the crashing is intermittent (only certain times are you teleporting to a location that causes my mod's worldgen code to go crazy and crash).

I'll keep trying to see if I can replicate it but for now, you could try turning off Cave Cavities or certain biomes (maybe Desert or Roofed Forest?) and see if it stops the issue. (if it does, please let me know so I can try and fix it!)

**Comment by TelepathicGrunt** [comment] 2019-12-15 15:17
Though if you have a world right now where entering the portal is causing a crash constantly, may I have the seed for the world and what coordinate you placed the portal in the Nether? (and what config options you have on if you changed any for that world)

**Comment by supersaiyansubtlety** [comment] 2019-12-15 21:48
Right, should have mentioned that it was happening most consistently with a portal from a custom dimension, although it was still happening less frequently with other portals. 
Why is UA affecting worldgen if I'm not using a UA world type?
Here's my [configs](https://www.dropbox.com/s/7ag5mc3ftjpibqk/dimensions-config.zip?dl=0) for randomportals and justenoughdimensions. The portal that was causing the most issues was the nether void portal, currently set to be horizontal using twilightforest's fiery metal blocks and activated with firecharges. You can easily swap out those items/blocks for vanilla minecraft blocks if you don't want to mess with TF. 
Also note that I'm using [this dev version](https://masa.dy.fi/tmp/minecraft/mods/jed/1.6.0-dev/justenoughdimensions-1.12.2-1.6.0-dev.20191213.231054.jar) of justenoughdimensions so my nether void can have nether structures. 
I was able to reliably produce the issue in any world if I just jumped back and forther though the portal several times.

**Comment by TelepathicGrunt** [comment] 2019-12-17 22:29
After downloading the mods and configs, I am still not able to reproduce the crashing issue at all which is quite odd. I may see about backporting the dimension feature from the 1.14 version of this mod as that could *potentially* fix the problem of crashing when teleporting to the overworld but I wouldn't hold my breath.

Though in your last reply, you said "Why is UA affecting worldgen if I'm not using a UA world type?". Can you explain this? Is the mod changing the overworld in default world types? Is the crashing occurring in default world type?

**Comment by TelepathicGrunt** [comment] 2019-12-18 16:57
The dimension is now backported to 1.12 under v.4.6.0. Download that version and try out your mods in some non-Ultra Amplified worldtypes. Since the mod won't affect the Overworld in non-Ultra Amplified worldtypes, teleporting to the Overworld should be working just fine. 

If the crash still happens, then I am not entirely sure if it's really my mod that is causing it. However, the fact that you said the crashing stops when not using my mod has me really stumped on what is the true root cause of this issue. Still, give the dimension version a shot!

**Comment by supersaiyansubtlety** [comment] 2019-12-18 20:56
First, yes, I've been using vanilla world types the whole time, and yet UA is still the only mod I can link the crash to. I'm starting to think it might be a 3-way conflict (as in RandomPortals, UA, and some other mod conflict, but only if all are present). 
I tried the latest version and the same crash occurs. 
Here's a zip with a world that I had the crash in, the debug.log it generated, and my full mod and config folders. 
[UAdebug.zip](https://www.dropbox.com/s/tsoa6a9647lwlsl/UAdebug.zip?dl=0)
Thanks for your help

**Comment by TelepathicGrunt** [comment] 2019-12-21 17:50
Looks like it has nothing to do with other mods. Instead, since I added the dimension to my mod, teleporting between that dimension and the Overworld when just using my mod alone will cause the same crashing to occur. 

I'm going to ask for help from others to try and get to the bottom of this but for now, you should remove my mod from your game when playing on worlds with dimensions. I'm really sorry about this issue and hopefully I can make progress soon on fixing it.

**Comment by supersaiyansubtlety** [comment] 2019-12-21 18:16
Ok, thanks for the help with this issue. 
Good luck tracking down the cause.

**Comment by TelepathicGrunt** [comment] 2019-12-22 16:27
The cause of the crashing has been found and fixed in the v.4.6.1 release of this mod! It was caused by the piece of code that displays how much of the world is created when creating a new world but it was firing when switching between dimensions and caused the crashing. That small QoL feature was removed as it isn't important for my mod and ended up causing us problems as seen here lol.

Thank you so much for reporting this and hopefully everything goes smoothly now when using my mod! :)

If the bug somehow persists or a new bug appears, please open a new issue here.

**Closed as completed by TelepathicGrunt** 2019-12-22 16:27 UTC
Labels: bug

**Comment by supersaiyansubtlety** [comment] 2019-12-22 22:33
Awesome, thanks! I'll DL that version and hopefully put it on my server : )
