### ISSUE TITLE
Flying ores

### ISSUE THREAD

**Issue by disastercube** [TelepathicGrunt/UltraAmplifiedMod#16] opened 2020-05-27 21:52 UTC
While exploring this dimension I stumped upon some flying ores inside a cave. Might be because when caverns get generated ores didn't get removed.

![2020-05-27_23 44 53](https://user-images.githubusercontent.com/62697421/83075963-00027400-a075-11ea-8066-c6701744309d.png)

**Comment by TelepathicGrunt** [comment] 2020-05-27 22:25
Were you using any other mod or just UA? Just want to rule out mod incompatibility first

**Comment by disastercube** [comment] 2020-05-27 22:31
Well yeah, but the only one that ads cave content was YUNG's better caves,
but that I'm pretty sure wasn't the cause. I've been using it for quite a
while and never saw it before. But hey, I might be wrong.

V čet., 28. maj 2020 00:26 je oseba TelepathicGrunt <
notifications@github.com> napisala:

**Comment by disastercube** [comment] 2020-05-27 22:33
Well yeah, but the only one that ads cave content was YUNG's better caves,
but that I'm pretty sure wasn't the cause. I've been using it for quite a
while and never saw it before. But hey, I might be wrong.

**Comment by TelepathicGrunt** [comment] 2020-05-27 22:40
yeah yung's caves could do that. If I recall, I helped him make a wrapper for carvers that turns them into features so that his mod has more control over them. however, the downside of this is that the carver is no longer always run before the ores which produces this issue. I'll let him know! 

If he can't fix it on his end, I can add a check for my carvers to carve out ores as well instead of just stone.

Also, here's a bonus pic of me cranking up the ore spawnrate trying to reproduce that issue until you mentioned YUNG's lol 
![image](https://user-images.githubusercontent.com/40846040/83079287-81441180-a049-11ea-920c-a4cf692cd749.png)

**Comment by disastercube** [comment] 2020-05-27 22:42
Nice 
Also, since we are at it, if you see those vines on the side of the dungeon. Well some have god like powers and decided to fly

**Comment by TelepathicGrunt** [comment] 2020-05-27 22:44
Yeah that too is part of this carver wrapper issue. Thank you for pointing that out so I can have carvers carve that too as backup. This issue means it should be possible for carvers to carve out any stone structure as well which is a big issue on his end.

**Comment by disastercube** [comment] 2020-05-27 22:47
But aren't both the dungeon and vines that come with it part of UA mod ?

**Comment by TelepathicGrunt** [comment] 2020-05-27 23:00
Yes but feature and carvers run in certain orders. It's a bit complicated.

So when feature are generated, they are suppose to pick and spawn in a 16x16 spot centered between 4 chunks. But they really can place blocks anywhere in that 32x32 area.

When the chunks are prepared for feature spawning, the carvers has carved all 4 chunks already so features never run into problems with carvers.

However, when YUNG's carver wrapper (which I help make and now is an accomplice to the problem lol), the carvers are moved out of the carver stage and into the feature stage. That means that the 4 chunks are not carved anymore before feature can be placed. So when ores spawn on the edge of the 16x16 area and reach into the next 16x16 chunk, that area will run the carver code but wont carve the ore because it did not expect there to be an ore there as they never would encounter them beforehand. Same with vines. 

It's a really tricky problem with worldgen and I know what he's trying to do is like super hard.

**Comment by disastercube** [comment] 2020-05-27 23:04
When a smaller mod creator tries to flex for helping a bigger mod creator lol. I'm joking btw, don't take my seriously.

**Comment by disastercube** [comment] 2020-05-27 23:11
Btw, your mod is amazing and all I truly think that but, it doesn't really blend with the vanilla style so many won't even consider using it. But there are biomes and ideas (such as Ocean with Ruins and Lukewarm Ocean that look like japanese terraced rice fields) in your mod that no other has. It's like a surface combined with a cave system and that would be really cool looking in a world generation . 
What do you think of starting a new mod that would also add a really nice and new looking cave systems and vanilla looks ? I'm talking about a world generation mod.

**Comment by TelepathicGrunt** [comment] 2020-05-27 23:17
It is a great thought but I'm kinda swamped with too much mods to work on right now rip. Maybe I'll make a PR to https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go and give them that kind of biome for them to use, maintain, and expand upon.

**Comment by disastercube** [comment] 2020-05-27 23:24
Well, whatever you're gonna try and do I wish you luck with it

**Comment by TelepathicGrunt** [comment] 2021-01-30 15:31
Closing this as yungs now fixed the floating ores and features by making the caves carvers again!

**Closed as completed by TelepathicGrunt** 2021-01-30 15:31 UTC
Labels: bug, Mod Incompatibility
