### ISSUE TITLE
UAD fine in single player but low FPS and chunks loading extra slow on server

### ISSUE THREAD

**Issue by VallenFrostweaver** [TelepathicGrunt/UltraAmplifiedMod#28] opened 2021-03-07 18:52 UTC
Minecraft 1.16.5
Forge 36.0.40
UAD 9.0.3

I have a pretty decent PC running the UAD dimension in a pack just fine. But when on a server (8GB RAM dedicated) the FPS drops and the chunks load very slowly if at all. Not sure this is something that is fixable but I do also realise that sometimes server play is overlooked and something is missed. Either way, I thought I'd post this and see what comes up or what specific info I can provide.

**Comment by TelepathicGrunt** [comment] 2021-03-07 18:57
Where is the fps and chuck loading being slowed in? The UAD dimension or outside it?

In UAD, due to the wide range of the terrain height, worldgen features are placed a lot more which slows down chunk generation (ore generation is the slowest but I can’t optimize it any further). As for fps, UAD’s terrain does stress the vanilla’s lighting and rendering system as there’s more visible blocks. I don’t know if there is a forge mod that optimizes rendering/lighting but if there is, that might be worth a shot. 

If the chunk gen and fps tanking is happening outside UAD, please definitely let me know and see if you an export a mod list instance for me to test

**Comment by TelepathicGrunt** [comment] 2021-04-13 20:02
oof. It's been a month and no new info. Since I cannot reproduce the low fps issue, I'll close this report

**Closed as completed by TelepathicGrunt** 2021-04-13 20:02 UTC
Labels: Need Further Info
